apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-challenge-app
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      containers:
        - name: flask-app
          image: deonsebastian/devops-challenge-1:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
