apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-service
spec:
  type: NodePort
  selector:
    app: devops-challenge-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
